from __future__ import annotations

import re
import unicodedata
from typing import Iterable


_NON_ALNUM_RE = re.compile(r"[^a-z0-9]+")
_MULTI_UNDERSCORE_RE = re.compile(r"_+")
_MULTI_SPACE_RE = re.compile(r"\s+")
_HAUSIE_PREFIX = "hausie_"


def slugify(value: str) -> str:
    """Normalize a string into a snake_case ASCII slug."""
    if value is None:
        return ""
    text = str(value).strip().lower()
    if not text:
        return ""
    normalized = unicodedata.normalize("NFKD", text)
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii")
    ascii_text = _NON_ALNUM_RE.sub("_", ascii_text)
    ascii_text = _MULTI_UNDERSCORE_RE.sub("_", ascii_text).strip("_")
    return ascii_text


def titleize(value: str) -> str:
    """Convert a slug or phrase into Title Case."""
    if value is None:
        return ""
    text = str(value).strip()
    if not text:
        return ""
    text = text.replace("_", " ").strip()
    return " ".join(word.capitalize() for word in text.split())


def _normalize_parts(parts: Iterable[str]) -> list[str]:
    """Normalize parts into slugs and drop empty values."""
    out = []
    for part in parts:
        if part is None:
            continue
        slug = slugify(part)
        if slug:
            out.append(slug)
    return out


def build_id(type_name: str, area: str | None = None, subject: str | None = None) -> str:
    """Build an id using {{type}}_{{area}}_{{subject}}."""
    if not type_name:
        raise ValueError("type_name is required to build an id")
    parts = _normalize_parts([type_name, area, subject])
    return "_".join(parts)


def build_object_id(area: str | None, subject: str | None) -> str:
    """Build an object id using {{area}}_{{subject}}."""
    parts = _normalize_parts([area, subject])
    if not parts:
        raise ValueError("area or subject is required to build an object id")
    return "_".join(parts)


def build_filename(type_name: str, area: str | None = None, subject: str | None = None, ext: str = "yaml") -> str:
    """Build a filename using {{type}}_{{area}}_{{subject}}.<ext>."""
    name = build_id(type_name, area, subject)
    return prefix_filename(f"{name}.{ext}")


def prefix_filename(filename: str) -> str:
    """Ensure filenames generated by Hausie start with the hausie_ prefix."""
    if not filename:
        return filename
    if filename.startswith(_HAUSIE_PREFIX):
        return filename
    return f"{_HAUSIE_PREFIX}{filename}"


def build_alias(type_name: str, area: str | None = None, subject: str | None = None) -> str:
    """Build an alias using {{Type}} - {{Area}} - {{Subject}}."""
    parts = [titleize(type_name), titleize(area), titleize(subject)]
    return " - ".join([p for p in parts if p])


def unique_slug(base: str, existing: set[str]) -> str:
    """Return a unique slug by appending numeric suffixes when needed."""
    base_slug = slugify(base)
    if not base_slug:
        base_slug = "item"
    if base_slug not in existing:
        return base_slug
    counter = 2
    while f"{base_slug}_{counter}" in existing:
        counter += 1
    return f"{base_slug}_{counter}"


def build_subject(prefix: str | None, name: str | None, existing: set[str] | None = None) -> str:
    """Build a subject slug, optionally ensuring uniqueness within a set."""
    prefix_slug = slugify(prefix) if prefix else ""
    name_slug = slugify(name) if name else ""
    subject = "_".join([p for p in [prefix_slug, name_slug] if p])
    if existing is None:
        return subject or "item"
    return unique_slug(subject or "item", existing)


def normalize_option_label(value: str | None) -> str:
    """Normalize labels for input_select options."""
    if value is None:
        return ""
    raw = str(value).strip()
    if not raw:
        return ""
    has_underscore = "_" in raw
    text = raw.replace("_", " ")
    text = _MULTI_SPACE_RE.sub(" ", text).strip()
    if has_underscore or text.islower():
        words = []
        for word in text.split():
            if word.isupper():
                words.append(word)
            else:
                words.append(word.capitalize())
        text = " ".join(words)
    return text


__all__ = [
    "slugify",
    "titleize",
    "build_id",
    "build_object_id",
    "build_filename",
    "prefix_filename",
    "build_alias",
    "unique_slug",
    "build_subject",
    "normalize_option_label",
]
